export const products = {
    Burgers: [
      {
        id: 1,
        title: "Classic Cheeseburger",
        description: "Juicy beef patty with cheddar cheese and lettuce.",
        real_price: 9.99,
        discounted_price: 7.99,
        image: "https://example.com/images/classic_cheeseburger.jpg",
      },
      {
        id: 2,
        title: "Bacon Burger",
        description: "Tender beef topped with crispy bacon and mayo.",
        real_price: 10.99,
        discounted_price: 8.99,
        image: "https://example.com/images/bacon_burger.jpg",
      },
      {
        id: 3,
        title: "Veggie Burger",
        description: "Delicious plant-based patty with fresh vegetables.",
        real_price: 8.99,
        discounted_price: 6.99,
        image: "https://example.com/images/veggie_burger.jpg",
      },
      {
        id: 4,
        title: "BBQ Burger",
        description: "Grilled beef with BBQ sauce and onion rings.",
        real_price: 11.49,
        discounted_price: 9.49,
        image: "https://example.com/images/bbq_burger.jpg",
      },
      {
        id: 5,
        title: "Spicy Jalapeño Burger",
        description: "Beef burger with jalapeños and spicy sauce.",
        real_price: 10.49,
        discounted_price: 8.49,
        image: "https://example.com/images/spicy_jalapeno_burger.jpg",
      },
    ],
    Pizzas: [
      {
        id: 6,
        title: "Margherita Pizza",
        description: "Classic pizza with fresh tomatoes and mozzarella cheese.",
        real_price: 12.99,
        discounted_price: 10.99,
        image: "https://example.com/images/margherita_pizza.jpg",
      },
      {
        id: 7,
        title: "Pepperoni Pizza",
        description: "Loaded with pepperoni and gooey mozzarella cheese.",
        real_price: 13.99,
        discounted_price: 11.99,
        image: "https://example.com/images/pepperoni_pizza.jpg",
      },
      {
        id: 8,
        title: "BBQ Chicken Pizza",
        description: "Grilled chicken with BBQ sauce and red onions.",
        real_price: 14.49,
        discounted_price: 12.49,
        image: "https://example.com/images/bbq_chicken_pizza.jpg",
      },
      {
        id: 9,
        title: "Vegetarian Pizza",
        description: "Topped with assorted vegetables and herbs.",
        real_price: 12.49,
        discounted_price: 10.49,
        image: "https://example.com/images/vegetarian_pizza.jpg",
      },
      {
        id: 10,
        title: "Meat Lover's Pizza",
        description: "Loaded with pepperoni, sausage, and bacon.",
        real_price: 15.99,
        discounted_price: 13.99,
        image: "https://example.com/images/meat_lovers_pizza.jpg",
      },
    ],
    Deals: [
      {
        id: 11,
        title: "Burger Combo",
        description: "Includes a burger, fries, and a drink.",
        real_price: 13.99,
        discounted_price: 10.99,
        image: "https://example.com/images/burger_combo.jpg",
      },
      {
        id: 12,
        title: "Pizza Party Pack",
        description: "Two pizzas with a side of garlic bread.",
        real_price: 25.99,
        discounted_price: 22.99,
        image: "https://example.com/images/pizza_party_pack.jpg",
      },
      {
        id: 13,
        title: "Family Meal Deal",
        description: "Four burgers, four fries, and four drinks.",
        real_price: 45.99,
        discounted_price: 39.99,
        image: "https://example.com/images/family_meal_deal.jpg",
      },
      {
        id: 14,
        title: "Mix and Match",
        description: "Choose any two burgers and two pizzas.",
        real_price: 32.99,
        discounted_price: 29.99,
        image: "https://example.com/images/mix_and_match.jpg",
      },
      {
        id: 15,
        title: "Friday Night Special",
        description: "Large pizza and two drinks at a discount.",
        real_price: 19.99,
        discounted_price: 16.99,
        image: "https://example.com/images/friday_night_special.jpg",
      },
    ],
    Salads: [
      {
        id: 16,
        title: "Caesar Salad",
        description: "Crisp romaine with Caesar dressing and croutons.",
        real_price: 8.99,
        discounted_price: 6.99,
        image: "https://example.com/images/caesar_salad.jpg",
      },
      {
        id: 17,
        title: "Greek Salad",
        description: "Tomatoes, cucumbers, olives, and feta cheese.",
        real_price: 9.49,
        discounted_price: 7.49,
        image: "https://example.com/images/greek_salad.jpg",
      },
      {
        id: 18,
        title: "Garden Salad",
        description: "Mixed greens with assorted vegetables.",
        real_price: 7.99,
        discounted_price: 5.99,
        image: "https://example.com/images/garden_salad.jpg",
      },
      {
        id: 19,
        title: "Spinach Salad",
        description: "Fresh spinach with strawberries and nuts.",
        real_price: 9.99,
        discounted_price: 7.99,
        image: "https://example.com/images/spinach_salad.jpg",
      },
      {
        id: 20,
        title: "Chicken Salad",
        description: "Grilled chicken on mixed greens with dressing.",
        real_price: 10.49,
        discounted_price: 8.49,
        image: "https://example.com/images/chicken_salad.jpg",
      },
      {
        id: 21,
        title: "Quinoa Salad",
        description: "Quinoa with mixed vegetables and a lemon vinaigrette.",
        real_price: 10.99,
        discounted_price: 8.99,
        image: "https://example.com/images/quinoa_salad.jpg",
      },
      {
        id: 22,
        title: "Cobb Salad",
        description: "Chopped salad with chicken, bacon, and avocado.",
        real_price: 11.49,
        discounted_price: 9.49,
        image: "https://example.com/images/cobb_salad.jpg",
      },
      {
        id: 23,
        title: "Asian Salad",
        description: "Mixed greens with sesame dressing and crispy noodles.",
        real_price: 9.49,
        discounted_price: 7.49,
        image: "https://example.com/images/asian_salad.jpg",
      },
      {
        id: 24,
        title: "Caprese Salad",
        description: "Fresh mozzarella, tomatoes, and basil drizzled with balsamic.",
        real_price: 10.49,
        discounted_price: 8.49,
        image: "https://example.com/images/caprese_salad.jpg",
      },
      {
        id: 25,
        title: "Taco Salad",
        description: "Tortilla bowl filled with seasoned meat and toppings.",
        real_price: 11.99,
        discounted_price: 9.99,
        image: "https://example.com/images/taco_salad.jpg",
      },
    ],
    Desserts: [
      {
        id: 26,
        title: "Chocolate Cake",
        description: "Rich chocolate cake with creamy frosting.",
        real_price: 4.99,
        discounted_price: 3.99,
        image: "https://example.com/images/chocolate_cake.jpg",
      },
      {
        id: 27,
        title: "Ice Cream Sundae",
        description: "Delicious sundae with toppings and whipped cream.",
        real_price: 5.49,
        discounted_price: 4.49,
        image: "https://example.com/images/ice_cream_sundae.jpg",
      },
      {
        id: 28,
        title: "Cheesecake",
        description: "Creamy cheesecake with a graham cracker crust.",
        real_price: 5.99,
        discounted_price: 4.99,
        image: "https://example.com/images/cheesecake.jpg",
      },
      {
        id: 29,
        title: "Brownie",
        description: "Fudgy chocolate brownie served warm.",
        real_price: 3.99,
        discounted_price: 2.99,
        image: "https://example.com/images/brownie.jpg",
      },
      {
        id: 30,
        title: "Apple Pie",
        description: "Homemade apple pie with a flaky crust.",
        real_price: 4.49,
        discounted_price: 3.49,
        image: "https://example.com/images/apple_pie.jpg",
      },
      {
        id: 31,
        title: "Tiramisu",
        description: "Classic Italian dessert with coffee and mascarpone.",
        real_price: 5.99,
        discounted_price: 4.99,
        image: "https://example.com/images/tiramisu.jpg",
      },
      {
        id: 32,
        title: "Panna Cotta",
        description: "Creamy dessert topped with berry sauce.",
        real_price: 4.99,
        discounted_price: 3.99,
        image: "https://example.com/images/panna_cotta.jpg",
      },
      {
        id: 33,
        title: "Mousse",
        description: "Light and airy chocolate mousse.",
        real_price: 4.49,
        discounted_price: 3.49,
        image: "https://example.com/images/mousse.jpg",
      },
      {
        id: 34,
        title: "Cupcake",
        description: "Delicious vanilla cupcake with frosting.",
        real_price: 2.99,
        discounted_price: 2.49,
        image: "https://example.com/images/cupcake.jpg",
      },
      {
        id: 35,
        title: "Fruit Tart",
        description: "Pastry filled with custard and topped with fresh fruit.",
        real_price: 5.49,
        discounted_price: 4.49,
        image: "https://example.com/images/fruit_tart.jpg",
      },
    ],
    Beverages: [
      {
        id: 36,
        title: "Cola",
        description: "Refreshing cola drink in a 12 oz can.",
        real_price: 1.99,
        discounted_price: 1.49,
        image: "https://example.com/images/cola.jpg",
      },
      {
        id: 37,
        title: "Lemonade",
        description: "Freshly squeezed lemonade served cold.",
        real_price: 2.49,
        discounted_price: 1.99,
        image: "https://example.com/images/lemonade.jpg",
      },
      {
        id: 38,
        title: "Iced Tea",
        description: "Chilled tea served with lemon.",
        real_price: 2.49,
        discounted_price: 1.99,
        image: "https://example.com/images/iced_tea.jpg",
      },
      {
        id: 39,
        title: "Coffee",
        description: "Freshly brewed coffee, hot or iced.",
        real_price: 2.49,
        discounted_price: 1.99,
        image: "https://example.com/images/coffee.jpg",
      },
      {
        id: 40,
        title: "Orange Juice",
        description: "Freshly squeezed orange juice.",
        real_price: 3.49,
        discounted_price: 2.99,
        image: "https://example.com/images/orange_juice.jpg",
      },
      {
        id: 41,
        title: "Milkshake",
        description: "Creamy milkshake in chocolate or vanilla.",
        real_price: 4.99,
        discounted_price: 3.99,
        image: "https://example.com/images/milkshake.jpg",
      },
      {
        id: 42,
        title: "Sparkling Water",
        description: "Refreshing sparkling water.",
        real_price: 2.99,
        discounted_price: 1.99,
        image: "https://example.com/images/sparkling_water.jpg",
      },
      {
        id: 43,
        title: "Hot Chocolate",
        description: "Rich hot chocolate topped with whipped cream.",
        real_price: 3.49,
        discounted_price: 2.49,
        image: "https://example.com/images/hot_chocolate.jpg",
      },
      {
        id: 44,
        title: "Smoothie",
        description: "Fruit smoothie made with fresh ingredients.",
        real_price: 4.99,
        discounted_price: 3.99,
        image: "https://example.com/images/smoothie.jpg",
      },
      {
        id: 45,
        title: "Herbal Tea",
        description: "Refreshing herbal tea with assorted flavors.",
        real_price: 2.49,
        discounted_price: 1.99,
        image: "https://example.com/images/herbal_tea.jpg",
      },
    ],
    Sandwiches: [
      {
        id: 46,
        title: "Club Sandwich",
        description: "Turkey, ham, and bacon with lettuce and tomato.",
        real_price: 10.49,
        discounted_price: 8.49,
        image: "https://example.com/images/club_sandwich.jpg",
      },
      {
        id: 47,
        title: "Grilled Cheese",
        description: "Classic grilled cheese sandwich with gooey cheese.",
        real_price: 6.99,
        discounted_price: 5.49,
        image: "https://example.com/images/grilled_cheese.jpg",
      },
      {
        id: 48,
        title: "Egg Salad Sandwich",
        description: "Creamy egg salad on fresh bread.",
        real_price: 6.49,
        discounted_price: 4.99,
        image: "https://example.com/images/egg_salad_sandwich.jpg",
      },
      {
        id: 49,
        title: "Veggie Sandwich",
        description: "Assorted vegetables with hummus on whole grain bread.",
        real_price: 7.99,
        discounted_price: 5.99,
        image: "https://example.com/images/veggie_sandwich.jpg",
      },
      {
        id: 50,
        title: "Ham and Cheese Sandwich",
        description: "Classic ham and cheese on a fresh roll.",
        real_price: 7.49,
        discounted_price: 5.49,
        image: "https://example.com/images/ham_cheese_sandwich.jpg",
      },
      {
        id: 51,
        title: "Tuna Sandwich",
        description: "Tuna salad with lettuce and tomato.",
        real_price: 7.99,
        discounted_price: 5.99,
        image: "https://example.com/images/tuna_sandwich.jpg",
      },
      {
        id: 52,
        title: "BLT Sandwich",
        description: "Bacon, lettuce, and tomato on toasted bread.",
        real_price: 8.49,
        discounted_price: 6.49,
        image: "https://example.com/images/blt_sandwich.jpg",
      },
      {
        id: 53,
        title: "Chicken Salad Sandwich",
        description: "Chicken salad with lettuce on whole grain bread.",
        real_price: 8.99,
        discounted_price: 6.99,
        image: "https://example.com/images/chicken_salad_sandwich.jpg",
      },
      {
        id: 54,
        title: "Philly Cheesesteak",
        description: "Steak, cheese, and peppers in a hoagie roll.",
        real_price: 9.99,
        discounted_price: 7.99,
        image: "https://example.com/images/philly_cheesesteak.jpg",
      },
      {
        id: 55,
        title: "Caprese Sandwich",
        description: "Fresh mozzarella, tomatoes, and basil on a baguette.",
        real_price: 8.49,
        discounted_price: 6.49,
        image: "https://example.com/images/caprese_sandwich.jpg",
      },
    ],
    Pasta: [
      {
        id: 56,
        title: "Spaghetti Bolognese",
        description: "Classic spaghetti with rich meat sauce.",
        real_price: 12.99,
        discounted_price: 10.99,
        image: "https://example.com/images/spaghetti_bolognese.jpg",
      },
      {
        id: 57,
        title: "Fettuccine Alfredo",
        description: "Creamy Alfredo sauce over fettuccine pasta.",
        real_price: 11.99,
        discounted_price: 9.99,
        image: "https://example.com/images/fettuccine_alfredo.jpg",
      },
      {
        id: 58,
        title: "Penne Arrabbiata",
        description: "Penne pasta in spicy tomato sauce.",
        real_price: 10.49,
        discounted_price: 8.49,
        image: "https://example.com/images/penne_arrabbiata.jpg",
      },
      {
        id: 59,
        title: "Lasagna",
        description: "Layers of pasta, meat, and cheese baked to perfection.",
        real_price: 14.99,
        discounted_price: 12.99,
        image: "https://example.com/images/lasagna.jpg",
      },
      {
        id: 60,
        title: "Pasta Primavera",
        description: "Pasta with fresh vegetables in a light sauce.",
        real_price: 11.49,
        discounted_price: 9.49,
        image: "https://example.com/images/pasta_primavera.jpg",
      },
      {
        id: 61,
        title: "Shrimp Scampi",
        description: "Shrimp sautéed in garlic butter over linguine.",
        real_price: 15.49,
        discounted_price: 13.49,
        image: "https://example.com/images/shrimp_scampi.jpg",
      },
      {
        id: 62,
        title: "Mac and Cheese",
        description: "Creamy macaroni and cheese baked to golden perfection.",
        real_price: 8.99,
        discounted_price: 6.99,
        image: "https://example.com/images/mac_and_cheese.jpg",
      },
      {
        id: 63,
        title: "Carbonara",
        description: "Pasta with bacon and creamy sauce.",
        real_price: 12.49,
        discounted_price: 10.49,
        image: "https://example.com/images/carbonara.jpg",
      },
      {
        id: 64,
        title: "Ravioli",
        description: "Stuffed pasta served with marinara sauce.",
        real_price: 11.99,
        discounted_price: 9.99,
        image: "https://example.com/images/ravioli.jpg",
      },
      {
        id: 65,
        title: "Baked Ziti",
        description: "Pasta baked with marinara and mozzarella cheese.",
        real_price: 10.99,
        discounted_price: 8.99,
        image: "https://example.com/images/baked_ziti.jpg",
      },
    ],
    Breakfast: [
      {
        id: 66,
        title: "Pancakes",
        description: "Fluffy pancakes served with syrup and butter.",
        real_price: 7.99,
        discounted_price: 5.99,
        image: "https://example.com/images/pancakes.jpg",
      },
      {
        id: 67,
        title: "Omelette",
        description: "Three-egg omelette with cheese and vegetables.",
        real_price: 8.49,
        discounted_price: 6.49,
        image: "https://example.com/images/omelette.jpg",
      },
      {
        id: 68,
        title: "French Toast",
        description: "Thick slices of bread dipped in egg batter and fried.",
        real_price: 6.99,
        discounted_price: 5.49,
        image: "https://example.com/images/french_toast.jpg",
      },
      {
        id: 69,
        title: "Breakfast Burrito",
        description: "Flour tortilla filled with eggs, cheese, and sausage.",
        real_price: 8.99,
        discounted_price: 6.99,
        image: "https://example.com/images/breakfast_burrito.jpg",
      },
      {
        id: 70,
        title: "Avocado Toast",
        description: "Smashed avocado on toasted bread with seasoning.",
        real_price: 7.49,
        discounted_price: 5.49,
        image: "https://example.com/images/avocado_toast.jpg",
      },
      {
        id: 71,
        title: "Breakfast Sandwich",
        description: "Egg, cheese, and sausage on a bagel.",
        real_price: 7.99,
        discounted_price: 5.99,
        image: "https://example.com/images/breakfast_sandwich.jpg",
      },
      {
        id: 72,
        title: "Smoothie Bowl",
        description: "Smoothie topped with granola and fresh fruit.",
        real_price: 8.49,
        discounted_price: 6.49,
        image: "https://example.com/images/smoothie_bowl.jpg",
      },
      {
        id: 73,
        title: "Yogurt Parfait",
        description: "Layered yogurt with granola and berries.",
        real_price: 5.99,
        discounted_price: 4.99,
        image: "https://example.com/images/yogurt_parfait.jpg",
      },
      {
        id: 74,
        title: "Chia Pudding",
        description: "Chia seeds soaked in almond milk with fruit.",
        real_price: 6.99,
        discounted_price: 5.49,
        image: "https://example.com/images/chia_pudding.jpg",
      },
      {
        id: 75,
        title: "Egg and Cheese Muffin",
        description: "Egg and cheese on an English muffin.",
        real_price: 5.49,
        discounted_price: 4.49,
        image: "https://example.com/images/egg_cheese_muffin.jpg",
      },
    ],
    Wraps: [
      {
        id: 76,
        title: "Chicken Wrap",
        description: "Grilled chicken with veggies wrapped in a tortilla.",
        real_price: 9.99,
        discounted_price: 7.99,
        image: "https://example.com/images/chicken_wrap.jpg",
      },
      {
        id: 77,
        title: "Veggie Wrap",
        description: "Fresh vegetables and hummus wrapped in a tortilla.",
        real_price: 8.49,
        discounted_price: 6.49,
        image: "https://example.com/images/veggie_wrap.jpg",
      },
      {
        id: 78,
        title: "Turkey Wrap",
        description: "Sliced turkey with lettuce and tomato in a wrap.",
        real_price: 9.49,
        discounted_price: 7.49,
        image: "https://example.com/images/turkey_wrap.jpg",
      },
      {
        id: 79,
        title: "Falafel Wrap",
        description: "Crispy falafel with lettuce and tahini sauce.",
        real_price: 8.99,
        discounted_price: 6.99,
        image: "https://example.com/images/falafel_wrap.jpg",
      },
      {
        id: 80,
        title: "BBQ Chicken Wrap",
        description: "Grilled chicken with BBQ sauce and veggies.",
        real_price: 9.99,
        discounted_price: 7.99,
        image: "https://example.com/images/bbq_chicken_wrap.jpg",
      },
      {
        id: 81,
        title: "Tuna Wrap",
        description: "Tuna salad with mixed greens in a wrap.",
        real_price: 8.99,
        discounted_price: 6.99,
        image: "https://example.com/images/tuna_wrap.jpg",
      },
      {
        id: 82,
        title: "Caprese Wrap",
        description: "Mozzarella, tomatoes, and basil in a wrap.",
        real_price: 8.49,
        discounted_price: 6.49,
        image: "https://example.com/images/caprese_wrap.jpg",
      },
      {
        id: 83,
        title: "Spicy Chicken Wrap",
        description: "Spicy chicken with lettuce and ranch sauce.",
        real_price: 9.49,
        discounted_price: 7.49,
        image: "https://example.com/images/spicy_chicken_wrap.jpg",
      },
      {
        id: 84,
        title: "Greek Wrap",
        description: "Chicken, feta, and olives in a wrap.",
        real_price: 9.99,
        discounted_price: 7.99,
        image: "https://example.com/images/greek_wrap.jpg",
      },
      {
        id: 85,
        title: "Buffalo Chicken Wrap",
        description: "Spicy buffalo chicken with lettuce in a wrap.",
        real_price: 9.99,
        discounted_price: 7.99,
        image: "https://example.com/images/buffalo_chicken_wrap.jpg",
      },
    ],
  };
  